#include "core/lunar.h"

#include <algorithm>
#include <gtest/gtest.h>

namespace {

TEST(SynodicMonthDays, MatchesTheCommonlyQuotedMeanValue) {
    // ~29.53059 days is the standard quoted mean synodic month.
    EXPECT_NEAR(core::SynodicMonthDays(), 29.530589, 1e-5);
}

// Reference illuminated fraction and age-since-new-moon values below are from the independent
// `pyephem` library (itself built on more complete lunar/solar theory than this project's own
// low-precision formula), computed once offline for each Julian date. Tolerances are set from
// the actual discrepancy observed against that reference across these cases (illuminated
// fraction within about 0.003, age within about 0.55 days), the same way this project verifies
// SGP4 against python-sgp4 (see README's Verification section).
struct ReferenceCase {
    const char* label;
    double julianDate;
    double illuminatedFraction;
    double ageDays;
};

constexpr ReferenceCase kReferenceCases[] = {
    {"2000-01-01", 2451544.50000, 0.27161, 24.06136},
    {"near a new moon, 2000-01-06", 2451550.25972, 0.00020, 0.00024},
    {"near a full moon, 2000-01-21", 2451564.69514, 0.99999, 14.43566},
    {"2026-09-22 (this project's present)", 2461305.50000, 0.78307, 10.85631},
    {"2026-01-01", 2461041.50000, 0.91400, 11.92828},
    {"1987-04-10 (Meeus's own worked-example date elsewhere in this suite)", 2446895.50000,
     0.82603, 11.46838},
    {"near a new moon, 2020-06-21", 2459022.00000, 0.00055, 0.22123},
    {"near a first quarter, 2026-09-18", 2461302.36368, 0.50121, 7.71999},
    {"near a last quarter, 2026-09-04", 2461287.82719, 0.50133, 22.59340},
};

TEST(LunarPhaseAt, MatchesTheIndependentPyephemReference) {
    for (const ReferenceCase& c : kReferenceCases) {
        const core::LunarPhase phase = core::LunarPhaseAt(c.julianDate);
        EXPECT_NEAR(phase.illuminatedFraction, c.illuminatedFraction, 0.01) << c.label;
        EXPECT_NEAR(phase.ageDays, c.ageDays, 0.6) << c.label;
    }
}

// Independently-documented reference moments, not generated by any astronomy library: an eclipse
// can only happen at the instant of an exact new moon (solar) or full moon (lunar), so each
// "greatest eclipse" time below -- the well-known, publicly published moment of maximum eclipse,
// from each event's Wikipedia article -- is a real-world illuminatedFraction of very nearly 0 or
// 1 (confirmed against pyephem: within 0.00002 of exactly 0 or 1 for all four). Julian dates were
// converted from each UTC time by hand (Unix-epoch JD 2440587.5 plus elapsed days).
TEST(LunarPhaseAt, MatchesKnownEclipseDates) {
    // 2021-05-26 11:18:44 UTC, greatest eclipse of a total lunar eclipse -> full moon.
    EXPECT_NEAR(core::LunarPhaseAt(2459360.971343).illuminatedFraction, 1.0, 0.01);

    // 2025-03-14 06:58:47 UTC, greatest eclipse of a total lunar eclipse -> full moon.
    EXPECT_NEAR(core::LunarPhaseAt(2460748.790822).illuminatedFraction, 1.0, 0.01);

    // 2024-04-08 18:18:29 UTC, greatest eclipse of a total solar eclipse -> new moon.
    EXPECT_NEAR(core::LunarPhaseAt(2460409.262836).illuminatedFraction, 0.0, 0.01);

    // 2023-10-14 18:00:40 UTC, greatest eclipse of an annular solar eclipse -> new moon.
    EXPECT_NEAR(core::LunarPhaseAt(2460232.250463).illuminatedFraction, 0.0, 0.01);
}

TEST(LunarPhaseAt, AgeIsNearHalfTheSynodicMonthAtKnownFullMoonEclipses) {
    const double halfMonth = core::SynodicMonthDays() / 2.0;
    EXPECT_NEAR(core::LunarPhaseAt(2459360.971343).ageDays, halfMonth, 0.6); // 2021-05-26
    EXPECT_NEAR(core::LunarPhaseAt(2460748.790822).ageDays, halfMonth, 0.6); // 2025-03-14
}

TEST(LunarPhaseAt, AgeIsNearTheWrapBoundaryAtKnownNewMoonEclipses) {
    // Age should be close to 0 -- but since it wraps at the synodic month, the true moment could
    // fall computed as just before the wrap (close to SynodicMonthDays()) instead of just after
    // (close to 0); the distance to the nearer of the two boundaries is what actually matters.
    const double synodicMonth = core::SynodicMonthDays();
    const auto wrapDistanceToZero = [synodicMonth](double ageDays) {
        return std::min(ageDays, synodicMonth - ageDays);
    };
    EXPECT_LT(wrapDistanceToZero(core::LunarPhaseAt(2460409.262836).ageDays), 0.6); // 2024-04-08
    EXPECT_LT(wrapDistanceToZero(core::LunarPhaseAt(2460232.250463).ageDays), 0.6); // 2023-10-14
}

TEST(LunarPhaseAt, IlluminatedFractionStaysInZeroToOne) {
    // Sweep a bit over four synodic months so every phase is exercised more than once.
    for (double jd = 2451545.0; jd < 2451545.0 + 4.0 * core::SynodicMonthDays(); jd += 0.5) {
        const core::LunarPhase phase = core::LunarPhaseAt(jd);
        EXPECT_GE(phase.illuminatedFraction, 0.0) << jd;
        EXPECT_LE(phase.illuminatedFraction, 1.0) << jd;
    }
}

TEST(LunarPhaseAt, AgeDaysStaysInZeroToTheSynodicMonth) {
    for (double jd = 2451545.0; jd < 2451545.0 + 4.0 * core::SynodicMonthDays(); jd += 0.5) {
        const core::LunarPhase phase = core::LunarPhaseAt(jd);
        EXPECT_GE(phase.ageDays, 0.0) << jd;
        EXPECT_LT(phase.ageDays, core::SynodicMonthDays()) << jd;
    }
}

TEST(LunarPhaseAt, AgeDaysAdvancesByAboutOneDayPerDay) {
    // Away from the wraparound at a new moon, age should track real elapsed time almost exactly
    // (the Moon's own mean motion is what defines it), not jump or run backward.
    const double jd = 2451550.5; // a few days after the 2000-01-06 new moon reference above
    const double age1 = core::LunarPhaseAt(jd).ageDays;
    const double age2 = core::LunarPhaseAt(jd + 1.0).ageDays;
    EXPECT_NEAR(age2 - age1, 1.0, 0.05);
}

TEST(LunarPhaseAt, NewMoonAndFullMoonAreOppositeInIlluminatedFraction) {
    // The mean elongation reaches 180 degrees (full moon) almost exactly half a synodic month
    // after it reaches 0 (new moon).
    const double newMoonJd = 2451550.25972; // near-exact new moon reference above
    const double fullMoonJd = newMoonJd + core::SynodicMonthDays() / 2.0;
    EXPECT_NEAR(core::LunarPhaseAt(newMoonJd).illuminatedFraction, 0.0, 0.01);
    EXPECT_NEAR(core::LunarPhaseAt(fullMoonJd).illuminatedFraction, 1.0, 0.01);
}

// Reference next-new-moon and next-full-moon times below are from the independent `pyephem`
// library, computed once offline for each starting Julian date. The tolerance (0.02 days, about
// half an hour) is tighter than LunarPhaseAt's own reference tests above: unlike ageDays,
// searching for the illuminatedFraction extremum uses its periodic correction terms, so it tracks
// the true event much more closely (observed within about 20 minutes of pyephem across these
// cases).
struct NextEventCase {
    const char* label;
    double fromJulianDate;
    double nextNewMoonJd;
    double nextFullMoonJd;
};

constexpr NextEventCase kNextEventCases[] = {
    {"2000-01-01", 2451544.5, 2451550.25948, 2451564.69476},
    {"2026-01-01", 2461041.5, 2461059.32771, 2461043.91864},
    {"2026-09-22 (this project's present)", 2461305.5, 2461324.15973, 2461310.20067},
    {"a few hours later, 2026-09-23 12:00", 2461306.0, 2461324.15973, 2461310.20067},
    {"2020-06-21 12:00, right after a known new moon", 2459022.0, 2459051.23120, 2459035.69749},
};

TEST(NextNewMoon, MatchesTheIndependentPyephemReference) {
    for (const NextEventCase& c : kNextEventCases) {
        const std::optional<double> next = core::NextNewMoon(c.fromJulianDate);
        ASSERT_TRUE(next.has_value()) << c.label;
        EXPECT_NEAR(*next, c.nextNewMoonJd, 0.02) << c.label;
    }
}

TEST(NextFullMoon, MatchesTheIndependentPyephemReference) {
    for (const NextEventCase& c : kNextEventCases) {
        const std::optional<double> next = core::NextFullMoon(c.fromJulianDate);
        ASSERT_TRUE(next.has_value()) << c.label;
        EXPECT_NEAR(*next, c.nextFullMoonJd, 0.02) << c.label;
    }
}

TEST(NextNewMoon, IsStrictlyAfterTheStartingDate) {
    for (const NextEventCase& c : kNextEventCases) {
        const std::optional<double> next = core::NextNewMoon(c.fromJulianDate);
        ASSERT_TRUE(next.has_value()) << c.label;
        EXPECT_GT(*next, c.fromJulianDate) << c.label;
    }
}

TEST(NextFullMoon, IsStrictlyAfterTheStartingDate) {
    for (const NextEventCase& c : kNextEventCases) {
        const std::optional<double> next = core::NextFullMoon(c.fromJulianDate);
        ASSERT_TRUE(next.has_value()) << c.label;
        EXPECT_GT(*next, c.fromJulianDate) << c.label;
    }
}

TEST(NextNewMoon, LandsWithinAFewMinutesOfIlluminatedFractionZero) {
    for (const NextEventCase& c : kNextEventCases) {
        const std::optional<double> next = core::NextNewMoon(c.fromJulianDate);
        ASSERT_TRUE(next.has_value()) << c.label;
        EXPECT_NEAR(core::LunarPhaseAt(*next).illuminatedFraction, 0.0, 0.001) << c.label;
    }
}

TEST(NextFullMoon, LandsWithinAFewMinutesOfIlluminatedFractionOne) {
    for (const NextEventCase& c : kNextEventCases) {
        const std::optional<double> next = core::NextFullMoon(c.fromJulianDate);
        ASSERT_TRUE(next.has_value()) << c.label;
        EXPECT_NEAR(core::LunarPhaseAt(*next).illuminatedFraction, 1.0, 0.001) << c.label;
    }
}

TEST(NextNewMoon, TwoConsecutiveCallsAreAboutOneSynodicMonthApart) {
    const std::optional<double> first = core::NextNewMoon(2451544.5);
    ASSERT_TRUE(first.has_value());
    const std::optional<double> second = core::NextNewMoon(*first + 1.0);
    ASSERT_TRUE(second.has_value());
    EXPECT_NEAR(*second - *first, core::SynodicMonthDays(), 0.5);
}

TEST(NextNewMoon, NulloptWhenMaxDaysIsTooShortToReachIt) {
    // The next new moon from this starting point is about 6 days away (see the reference table
    // above); a maxDays budget far shorter than that must not find a wrong answer, or loop
    // forever, just report nothing.
    EXPECT_EQ(core::NextNewMoon(2451544.5, /*stepDays=*/1.0, /*maxDays=*/2.0), std::nullopt);
}

TEST(NextFullMoon, NulloptWhenMaxDaysIsTooShortToReachIt) {
    EXPECT_EQ(core::NextFullMoon(2461305.5, /*stepDays=*/1.0, /*maxDays=*/2.0), std::nullopt);
}

} // namespace
